### ISSUE TITLE
path_management.m  problem

### ISSUE THREAD

**Issue by Galway1986** [stabix/stabix#58]
Hi, I am a new learner of matlab. I'm trying to use stabix tool to do some analysis. When I start to run the path_management.m file, it was always  reported an error: Undefined function 'path2cell' for input arguments of type 'char'. How can I figure this out? Do I need to make some pre-setting before run this file.
Many thanks for your answer.

**Comment by DavidMercier** [comment]
Hi Ming,

No problem, don't hesitate to ask me your questions.

The function path2cell is in the 'util' folder, but Matlab should find it automatically. Try to run demo.m instead of path_management.m. The path management is inside the demo file too.
If it doesn't work, try with the attached file to this message by replacing the original 'path_management' file in the Stabix repository.

Anyway, this issue is weird. On what system do you work (Mac, Linux, Windows...) ?
Maybe it's just a wrong path definition in the code...
In case, we don't find a solution the best is for me to connect myself to your computer with TeamViewer and to look into the code directly...
Let's see and good luck.

Best regards.
David MERCIER
[path_management.zip](https://github.com/stabix/stabix/files/907326/path_management.zip)
