### ISSUE TITLE
Import data issue using ".ctf" file from CHANNEL5

### ISSUE THREAD

**Issue by yangliu91** [stabix/stabix#64]
Hi,

I am sorry that I am new to STABiX, my question might be very amateur. I was trying to analysis EBSD data exported from CHANNEL 5. And I met a few issues.

1. I use "MTEX" to import my ".ctf" file to STABiX and I was informed following information 
![image](https://user-images.githubusercontent.com/45270686/48921672-59ca2280-ee6f-11e8-8429-5304546eb23e.png)
2. The data loading complete after a long waiting despite the "warning" and the program got "frozen" all the time. My click on GUI buttons has no response (I checked the CPU and Memory status, CPU less than 40% and memory less than 50%). And the EBSD map will show after a long waiting time but any calculation process seems impossible because I did not know if the calculation process is undergoing or not. Another message will pop up if I tried to stop the program
![image](https://user-images.githubusercontent.com/45270686/48921906-08bb2e00-ee71-11e8-9187-fea0039beb7f.png)

Should I use a much much smaller data section which contains fewer grains? Or the long processing time is related to "CHANNEL 5" file?

Many thanks~

**Comment by DavidMercier** [comment]
Hi, thank you for the feedback.
The warnings are only warnings, so don't worry. It is just an information about data file...
How many grains and grain boundaries are defined in your ebsd data file?
It's better if it's not too huge... and the last error message is because the import process of your data is not finished, I think.
Send me your ebsd file if you want, then I can try to check with my configuration, otherwise it  is a good idea to try with smaller data section.
Good luck.
