### ISSUE TITLE
STABiX causing interference with MTEX plotting?

### ISSUE THREAD

**Issue by MGRashed** [stabix/stabix#73]
When I plot something in MTEX alone, everything is fine. Then I open STABiX and do some calculation, but afterwards the MTEX plotting becomes kind of rough (on the edges) even though STABiX is closed. I have to restart MATLAB to get MTEX working to the usual niceness again.

Maybe there is some setting in STABiX that is causing some change in MTEX, and it remains in the current MATLAB session until restarted?

**Comment by DavidMercier** [comment]
I think it is because in MTEX, traditional Matlab functions (ie plot, abs...) are overwritten by MTEX functions: https://mtex-toolbox.github.io/files/doc/funcref_alph.html

Then, when the usual Matlab plot function is called in a Stabix or another Matlab code for example, the Mtex function comes first and arguments are wrong, which may imply the crash of Matlab in the case of loops...
This is my understanding and I have seen some similar issue in the past, but nothing to do... just close Matlab once you use MTEX in the first raw.

**Comment by MGRashed** [comment]
Aha, thanks for the clarification.
